package com.example.springdemo.wytest.demowytest.test;

import com.google.gson.GsonBuilder;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;



import java.lang.reflect.Constructor;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Test {

    public static void main(String[] args) {
        String orderName="[甲] 上消化道造影";
        String newOrderName = orderName.indexOf("[")>=0?(orderName.indexOf("]")==orderName.length()-1?"":orderName.substring(orderName.indexOf("]"))+1):orderName;
        log.info("newOrderName:{}",newOrderName);
        String sql="[甲] ${inpNo}上消化道${hosNum}造影";
        char[] array = sql.toCharArray();
        int startIndex = sql.indexOf("${",0);
        log.info("$起始位置为{}",startIndex);
        for (int i=0;i<array.length;i++){
            log.info("第{}位的字符为：{}",i,array[i]);
        }
        Constructor<?>[] constructors = ExcOrder.class.getConstructors();
        for(Constructor<?> constructorItem:constructors){
         log.info("构造器：{}",constructorItem.getClass());
            log.info("构造器：{}",constructorItem.getAnnotatedReceiverType());
        }


        String listJsonStr = "[\n" +
                "        {\n" +
                "            \"patientName\":\"叶小书\",\n" +
                "            \"orderList\":[\n" +
                "                {\n" +
                "                    \"bedNo\":\"10\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1613711911905\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98928\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0006801\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\n" +
                "                    \"orderNo\":\"382ef20b6b714ec59cc5628ad50121da\",\n" +
                "                    \"orderSn\":\"06801\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673358\",\n" +
                "                    \"patientName\":\"叶小书\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"50\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"10\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1613711911905\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98928\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":8,\n" +
                "                    \"medDoesUnit\":\"mg\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0006802\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[乙] 注射用氯诺昔康 8mg\",\n" +
                "                    \"orderNo\":\"30732fd21b904c0697679d4e382ae689\",\n" +
                "                    \"orderSn\":\"06802\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673358\",\n" +
                "                    \"patientName\":\"叶小书\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"382ef20b6b714ec59cc5628ad50121da\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"50\"\n" +
                "                }\n" +
                "            ],\n" +
                "            \"wardName\":\"骨科一病区\",\n" +
                "            \"bedNo\":\"10\",\n" +
                "            \"useTime\":\"2021-03-01\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"patientName\":\"王家友\",\n" +
                "            \"orderList\":[\n" +
                "                {\n" +
                "                    \"bedNo\":\"33\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1614068421907\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98929\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0008901\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 法莫替丁氯化钠注射液 100ml:法莫替丁20mg+氯化钠0.9g\",\n" +
                "                    \"orderNo\":\"942893576b3940d3a0ec1860cb847c69\",\n" +
                "                    \"orderSn\":\"08901\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673362\",\n" +
                "                    \"patientName\":\"王家友\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"72\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"33\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1614068450226\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98929\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0009001\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\n" +
                "                    \"orderNo\":\"847a026cb89e415ea9f3ad35975cb539\",\n" +
                "                    \"orderSn\":\"09001\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673362\",\n" +
                "                    \"patientName\":\"王家友\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"72\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"33\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1614068450226\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98929\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":8,\n" +
                "                    \"medDoesUnit\":\"mg\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0009002\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[乙] 注射用氯诺昔康 8mg\",\n" +
                "                    \"orderNo\":\"dfa29c00063b4125a8f026daea4552e1\",\n" +
                "                    \"orderSn\":\"09002\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673362\",\n" +
                "                    \"patientName\":\"王家友\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"847a026cb89e415ea9f3ad35975cb539\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"72\"\n" +
                "                }\n" +
                "            ],\n" +
                "            \"wardName\":\"骨科一病区\",\n" +
                "            \"bedNo\":\"33\",\n" +
                "            \"useTime\":\"2021-03-01\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"patientName\":\"赖春祥\",\n" +
                "            \"orderList\":[\n" +
                "                {\n" +
                "                    \"bedNo\":\"38\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1613967647025\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98930\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0004401\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\n" +
                "                    \"orderNo\":\"f376e2e6c69f45d788c107ee702918cc\",\n" +
                "                    \"orderSn\":\"04401\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7671675\",\n" +
                "                    \"patientName\":\"赖春祥\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"44\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"38\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1613967647025\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98930\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":1.5,\n" +
                "                    \"medDoesUnit\":\"g\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0004402\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 注射用头孢曲松钠 1.5g*10瓶/盒\",\n" +
                "                    \"orderNo\":\"2fab6035d9bd4e66baceb88ce086bd30\",\n" +
                "                    \"orderSn\":\"04402\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7671675\",\n" +
                "                    \"patientName\":\"赖春祥\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"f376e2e6c69f45d788c107ee702918cc\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"44\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"38\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1613969334803\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98930\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0005501\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\n" +
                "                    \"orderNo\":\"c0f716a7547f4b2e9b3732ea94308a50\",\n" +
                "                    \"orderSn\":\"05501\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7671675\",\n" +
                "                    \"patientName\":\"赖春祥\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"44\"\n" +
                "                }\n" +
                "            ],\n" +
                "            \"wardName\":\"骨科一病区\",\n" +
                "            \"bedNo\":\"38\",\n" +
                "            \"useTime\":\"2021-03-01\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"patientName\":\"张淑华\",\n" +
                "            \"orderList\":[\n" +
                "                {\n" +
                "                    \"bedNo\":\"05\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1613706835752\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98931\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0005001\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\n" +
                "                    \"orderNo\":\"4775e98d75ba4e2ba5b20f882a337cbf\",\n" +
                "                    \"orderSn\":\"05001\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673364\",\n" +
                "                    \"patientName\":\"张淑华\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"57\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"05\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1613706835752\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98931\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":8,\n" +
                "                    \"medDoesUnit\":\"mg\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0005002\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[乙] 注射用氯诺昔康 8mg\",\n" +
                "                    \"orderNo\":\"ff5a998b451647c2b0c06e9bf5f20365\",\n" +
                "                    \"orderSn\":\"05002\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673364\",\n" +
                "                    \"patientName\":\"张淑华\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"4775e98d75ba4e2ba5b20f882a337cbf\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"57\"\n" +
                "                }\n" +
                "            ],\n" +
                "            \"wardName\":\"骨科一病区\",\n" +
                "            \"bedNo\":\"05\",\n" +
                "            \"useTime\":\"2021-03-01\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"patientName\":\"刘贵英\",\n" +
                "            \"orderList\":[\n" +
                "                {\n" +
                "                    \"bedNo\":\"18\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1613792570684\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98939\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0005401\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\n" +
                "                    \"orderNo\":\"2a27029bc236469daf29e2369f9861c1\",\n" +
                "                    \"orderSn\":\"05401\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673404\",\n" +
                "                    \"patientName\":\"刘贵英\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"57\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"18\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1613792570684\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98939\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":8,\n" +
                "                    \"medDoesUnit\":\"mg\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0005402\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[乙] 注射用氯诺昔康 8mg\",\n" +
                "                    \"orderNo\":\"251162c3404c4e88a64a17367ae47d8f\",\n" +
                "                    \"orderSn\":\"05402\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673404\",\n" +
                "                    \"patientName\":\"刘贵英\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"2a27029bc236469daf29e2369f9861c1\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"57\"\n" +
                "                }\n" +
                "            ],\n" +
                "            \"wardName\":\"骨科一病区\",\n" +
                "            \"bedNo\":\"18\",\n" +
                "            \"useTime\":\"2021-03-01\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"patientName\":\"申天芬\",\n" +
                "            \"orderList\":[\n" +
                "                {\n" +
                "                    \"bedNo\":\"22\",\n" +
                "                    \"dayQty\":\"1\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"bid\",\n" +
                "                    \"freqName\":\"2次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1614052666936\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98945\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0004201\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\n" +
                "                    \"orderNo\":\"17f9a46a18bd4bf3866c3c36f0f59211\",\n" +
                "                    \"orderSn\":\"04201\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673414\",\n" +
                "                    \"patientName\":\"申天芬\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"2\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"50\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"22\",\n" +
                "                    \"dayQty\":\"2\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"bid\",\n" +
                "                    \"freqName\":\"2次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1614052666936\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98945\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":1,\n" +
                "                    \"medDoesUnit\":\"g\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0004202\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 注射用头孢呋辛钠 0.5g\",\n" +
                "                    \"orderNo\":\"bff1df318f0e4626b2c3ff91361df4cd\",\n" +
                "                    \"orderSn\":\"04202\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673414\",\n" +
                "                    \"patientName\":\"申天芬\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"17f9a46a18bd4bf3866c3c36f0f59211\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"4\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"50\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"22\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1614052768245\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98945\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0004501\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\n" +
                "                    \"orderNo\":\"1db99fac2c124387a71b545bd4ab60cf\",\n" +
                "                    \"orderSn\":\"04501\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673414\",\n" +
                "                    \"patientName\":\"申天芬\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"50\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"22\",\n" +
                "                    \"dayQty\":\"0\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qd\",\n" +
                "                    \"freqName\":\"1次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1614052768245\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98945\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":8,\n" +
                "                    \"medDoesUnit\":\"mg\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0004502\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[乙] 注射用氯诺昔康 8mg\",\n" +
                "                    \"orderNo\":\"8ac1ec66a5294835a37cc07cb67f1f15\",\n" +
                "                    \"orderSn\":\"04502\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673414\",\n" +
                "                    \"patientName\":\"申天芬\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"1db99fac2c124387a71b545bd4ab60cf\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"1\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"50\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"22\",\n" +
                "                    \"dayQty\":\"1\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"bid\",\n" +
                "                    \"freqName\":\"2次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 15:00GP_1614052666936\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98945\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":100,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 15:0004201\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\n" +
                "                    \"orderNo\":\"17f9a46a18bd4bf3866c3c36f0f59211\",\n" +
                "                    \"orderSn\":\"04201\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673414\",\n" +
                "                    \"patientName\":\"申天芬\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"2\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"50\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"22\",\n" +
                "                    \"dayQty\":\"2\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"bid\",\n" +
                "                    \"freqName\":\"2次/天\",\n" +
                "                    \"gender\":\"女\",\n" +
                "                    \"groupId\":\"2021-03-01 15:00GP_1614052666936\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98945\",\n" +
                "                    \"insType\":\"重庆医保\",\n" +
                "                    \"medDoes\":1,\n" +
                "                    \"medDoesUnit\":\"g\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 15:0004202\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 注射用头孢呋辛钠 0.5g\",\n" +
                "                    \"orderNo\":\"bff1df318f0e4626b2c3ff91361df4cd\",\n" +
                "                    \"orderSn\":\"04202\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673414\",\n" +
                "                    \"patientName\":\"申天芬\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"17f9a46a18bd4bf3866c3c36f0f59211\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007874\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"4\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY002\",\n" +
                "                    \"wayName\":\"静脉输液(超过一组)\",\n" +
                "                    \"yearsOld\":\"50\"\n" +
                "                }\n" +
                "            ],\n" +
                "            \"wardName\":\"骨科一病区\",\n" +
                "            \"bedNo\":\"22\",\n" +
                "            \"useTime\":\"2021-03-01\"\n" +
                "        },\n" +
                "        {\n" +
                "            \"patientName\":\"沈八可\",\n" +
                "            \"orderList\":[\n" +
                "                {\n" +
                "                    \"bedNo\":\"07\",\n" +
                "                    \"dayQty\":\"2\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qid\",\n" +
                "                    \"freqName\":\"4次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 09:00GP_1614327527267\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98971\",\n" +
                "                    \"insType\":\"自费\",\n" +
                "                    \"medDoes\":2,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 09:0001901\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 肝素钠注射液 1.25万单位：2ml\",\n" +
                "                    \"orderNo\":\"4173b31b57b740d099d353fe4a3b36bf\",\n" +
                "                    \"orderSn\":\"01901\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673556\",\n" +
                "                    \"patientName\":\"沈八可\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007884\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"4\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"30\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"07\",\n" +
                "                    \"dayQty\":\"2\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qid\",\n" +
                "                    \"freqName\":\"4次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 12:00GP_1614327527267\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98971\",\n" +
                "                    \"insType\":\"自费\",\n" +
                "                    \"medDoes\":2,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 12:0001901\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 肝素钠注射液 1.25万单位：2ml\",\n" +
                "                    \"orderNo\":\"4173b31b57b740d099d353fe4a3b36bf\",\n" +
                "                    \"orderSn\":\"01901\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673556\",\n" +
                "                    \"patientName\":\"沈八可\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007884\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"4\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"30\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"07\",\n" +
                "                    \"dayQty\":\"2\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qid\",\n" +
                "                    \"freqName\":\"4次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 17:00GP_1614327527267\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98971\",\n" +
                "                    \"insType\":\"自费\",\n" +
                "                    \"medDoes\":2,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 17:0001901\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 肝素钠注射液 1.25万单位：2ml\",\n" +
                "                    \"orderNo\":\"4173b31b57b740d099d353fe4a3b36bf\",\n" +
                "                    \"orderSn\":\"01901\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673556\",\n" +
                "                    \"patientName\":\"沈八可\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007884\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"4\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"30\"\n" +
                "                },\n" +
                "                {\n" +
                "                    \"bedNo\":\"07\",\n" +
                "                    \"dayQty\":\"2\",\n" +
                "                    \"doctorAdvice\":\"\",\n" +
                "                    \"excDeptCode\":\"10007874\",\n" +
                "                    \"excDeptName\":\"西药房\",\n" +
                "                    \"freq\":\"qid\",\n" +
                "                    \"freqName\":\"4次/天\",\n" +
                "                    \"gender\":\"男\",\n" +
                "                    \"groupId\":\"2021-03-01 22:00GP_1614327527267\",\n" +
                "                    \"groupMedFlag\":\"\",\n" +
                "                    \"hosNum\":\"2901349\",\n" +
                "                    \"inpNo\":\"98971\",\n" +
                "                    \"insType\":\"自费\",\n" +
                "                    \"medDoes\":2,\n" +
                "                    \"medDoesUnit\":\"ml\",\n" +
                "                    \"medFlowRate\":\"0\",\n" +
                "                    \"medUseMethod\":\"\",\n" +
                "                    \"newOrderSn\":\"2021-03-01 22:0001901\",\n" +
                "                    \"nodeCode\":\"2901349\",\n" +
                "                    \"orderAuditNo\":\"\",\n" +
                "                    \"orderAuditStatus\":\"4\",\n" +
                "                    \"orderClass\":\"长期\",\n" +
                "                    \"orderCode\":\"\",\n" +
                "                    \"orderFlag\":\"\",\n" +
                "                    \"orderName\":\"[甲] 肝素钠注射液 1.25万单位：2ml\",\n" +
                "                    \"orderNo\":\"4173b31b57b740d099d353fe4a3b36bf\",\n" +
                "                    \"orderSn\":\"01901\",\n" +
                "                    \"orderTime\":null,\n" +
                "                    \"orderType\":\"西药\",\n" +
                "                    \"patientId\":\"7673556\",\n" +
                "                    \"patientName\":\"沈八可\",\n" +
                "                    \"planExcTime\":null,\n" +
                "                    \"porderNo\":\"\",\n" +
                "                    \"printStatus\":\"0\",\n" +
                "                    \"sendDeptCode\":\"10007884\",\n" +
                "                    \"sendManName\":\"\",\n" +
                "                    \"sendTime\":null,\n" +
                "                    \"totalQty\":\"4\",\n" +
                "                    \"useTime\":null,\n" +
                "                    \"wardName\":\"骨科一病区\",\n" +
                "                    \"wardNo\":\"HL14\",\n" +
                "                    \"wayCode\":\"WY008\",\n" +
                "                    \"wayName\":\"静脉输液\",\n" +
                "                    \"yearsOld\":\"30\"\n" +
                "                }\n" +
                "            ],\n" +
                "            \"wardName\":\"骨科一病区\",\n" +
                "            \"bedNo\":\"07\",\n" +
                "            \"useTime\":\"2021-03-01\"\n" +
                "        }\n" +
                "    ]";
String listJsonStr2 = "[{\"patientName\":\"张淑华\",\"orderList\":[{\"bedNo\":\"05\",\"dayQty\":\"0\",\"doctorAdvice\":\"\",\"excDeptCode\":\"10007874\",\"excDeptName\":\"西药房\",\"freq\":\"qd\",\"freqName\":\"1次/天\",\"gender\":\"女\",\"groupId\":\"2021-03-02 09:00GP_1613706835752\",\"groupMedFlag\":\"\",\"hosNum\":\"2901349\",\"inpNo\":\"98931\",\"insType\":\"重庆医保\",\"medDoes\":100,\"medDoesUnit\":\"ml\",\"medFlowRate\":\"0\",\"medUseMethod\":\"\",\"newOrderSn\":\"2021-03-02 09:0005001\",\"nodeCode\":\"2901349\",\"orderAuditNo\":\"\",\"orderAuditStatus\":\"4\",\"orderClass\":\"长期\",\"orderCode\":\"\",\"orderFlag\":\"\",\"orderName\":\"[甲] 0.9％氯化钠注射液 0.9％*100ml（直立式聚丙烯输液袋双口管）\",\"orderNo\":\"4775e98d75ba4e2ba5b20f882a337cbf\",\"orderSn\":\"05001\",\"orderTime\":null,\"orderType\":\"西药\",\"patientId\":\"7673364\",\"patientName\":\"张淑华\",\"planExcTime\":null,\"porderNo\":\"\",\"printStatus\":\"0\",\"sendDeptCode\":\"10007874\",\"sendManName\":\"\",\"sendTime\":null,\"totalQty\":\"1\",\"useTime\":null,\"wardName\":\"骨科一病区\",\"wardNo\":\"HL14\",\"wayCode\":\"WY008\",\"wayName\":\"静脉输液\",\"yearsOld\":\"57\"},{\"bedNo\":\"05\",\"dayQty\":\"0\",\"doctorAdvice\":\"\",\"excDeptCode\":\"10007874\",\"excDeptName\":\"西药房\",\"freq\":\"qd\",\"freqName\":\"1次/天\",\"gender\":\"女\",\"groupId\":\"2021-03-02 09:00GP_1613706835752\",\"groupMedFlag\":\"\",\"hosNum\":\"2901349\",\"inpNo\":\"98931\",\"insType\":\"重庆医保\",\"medDoes\":8,\"medDoesUnit\":\"mg\",\"medFlowRate\":\"0\",\"medUseMethod\":\"\",\"newOrderSn\":\"2021-03-02 09:0005002\",\"nodeCode\":\"2901349\",\"orderAuditNo\":\"\",\"orderAuditStatus\":\"4\",\"orderClass\":\"长期\",\"orderCode\":\"\",\"orderFlag\":\"\",\"orderName\":\"[乙] 注射用氯诺昔康 8mg\",\"orderNo\":\"ff5a998b451647c2b0c06e9bf5f20365\",\"orderSn\":\"05002\",\"orderTime\":null,\"orderType\":\"西药\",\"patientId\":\"7673364\",\"patientName\":\"张淑华\",\"planExcTime\":null,\"porderNo\":\"4775e98d75ba4e2ba5b20f882a337cbf\",\"printStatus\":\"0\",\"sendDeptCode\":\"10007874\",\"sendManName\":\"\",\"sendTime\":null,\"totalQty\":\"1\",\"useTime\":null,\"wardName\":\"骨科一病区\",\"wardNo\":\"HL14\",\"wayCode\":\"WY008\",\"wayName\":\"静脉输液\",\"yearsOld\":\"57\"}],\"wardName\":\"骨科一病区\",\"bedNo\":\"05\",\"useTime\":\"2021-03-02\"}]";
        List<ExcOrder> list = JSONArray.parseArray(listJsonStr2, ExcOrder.class);
        log.info("str 转换成 对象之后：{}",list);

    }
}
